
# ansible-playbook 01_create_dir.yml
---
- name: myplaybookname
  hosts: 172.31.92.200
  become: true
  become_user: root
  
  tasks:
  - name: Create a directory
    file:
     path: /home/ansibleadmin/playbook_dir
     mode: 755
     owner: ansibleadmin
     group: ansibleadmin
     state: directory
...