#
# 2 ways of executing it - Static and Dynamic inventory
#
# Approach 1: Update inventory in /etc/ansible/hosts file
# Command:
#     ansible-playbook 

---
- name: install apache
  hosts: my-ansible-client
  become: true
  become_user: root

  tasks:
  - name: Install Apache Httpd
    yum: name=httpd state=present

  - name: Start Apache httpd
    service: name=httpd state=started
...
