#
# 
# Refer to "dynamic_inventory1" for dynamic inventory example
# ansible-playbook -i dynamic_inventory1 11_playbook-apache_dyninv.yml
#
---
- name: install apache
  hosts: new-dyn-inv
  become: true
  become_user: root

  tasks:
  - name: Install Apache Httpd
    yum: name=httpd state=present

  - name: Start Apache httpd
    service: name=httpd state=started
...
