---
- name: Pre, Post tasks and Tags Example
  hosts: localhost
  #become: true
  tags:
    - harishtallam
  pre_tasks:
    - debug: msg="Started with tag - harishtallam"
  tasks:
    - name: Execution in tasks
      debug: msg="Now we are in tasks tag"
  post_tasks:
    - debug: msg="Now we are in post tasks"
- name: Play without tags
  hosts: localhost
      #become: true
  tasks: 
   - name: Command to list files
     shell: ls -lrt > harishtallam.txt

# ansible-playbook preposttag.yml --list-tags
# ansible-playbook preposttag.yml --tag harishtallam
